import {
	isConvertibleToDate,
	isPlainObject,
	isString,
} from '../../util';
import { GridPlainRows } from './generate-rows';

export type ColumnKey = string;
export type ColumnValue = unknown;
export type ColumnType = 'string' | 'date' | 'expander';
export type ColumnTypesMap = Record<ColumnKey, ColumnType>;
export type ColumnGenerator<C> = (id: ColumnKey) => C;
export type ColumnFactory<C> = Record<ColumnType, ColumnGenerator<C>>;

export const AUTO_GENERATED_PREFIXER = '##auto-generated##';

export function generateColumns<C>(
	plainRows: GridPlainRows,
	columnFactory: ColumnFactory<C>
): C[] {
	const columnTypesMap = getColumnTypesMap(plainRows);
	const columnTypesEntries = Object.entries(columnTypesMap);

	return columnTypesEntries.map(([columnKey, columnType]) =>
		columnFactory[columnType](columnKey)
	);
}

export function getColumnTypesMap(plainRows: GridPlainRows): ColumnTypesMap {
	const columnKeyValueMapper: Record<ColumnKey, ColumnValue[]> = {};

	for (const row of plainRows) {
		for (const [columnKey, columnValue] of Object.entries(row)) {
			columnKeyValueMapper[columnKey] =
				columnKeyValueMapper[columnKey] ?? [];
			columnKeyValueMapper[columnKey].push(columnValue);
		}
	}

	const columnSchemaMap: ColumnTypesMap = {};

	for (const [columnKey, columnValues] of Object.entries(
		columnKeyValueMapper
	)) {
		if (isAutoGeneratedColumn(columnValues)) {
			continue;
		} else if (isExpandableColumn(columnValues)) {
			columnSchemaMap[columnKey] = 'expander';
		} else if (isDateColumn(columnValues)) {
			columnSchemaMap[columnKey] = 'date';
		} else if (isStringColumn(columnValues)) {
			columnSchemaMap[columnKey] = 'string';
		} else {
			columnSchemaMap[columnKey] = 'string';
		}
		// TODO: add helper for boolean values,
	}

	return columnSchemaMap;
}

export function isAutoGeneratedValue(value: ColumnValue) {
	return isString(value) && value.includes(AUTO_GENERATED_PREFIXER);
}

function isAutoGeneratedColumn(columnValues: ColumnValue[]) {
	return columnValues.every(isAutoGeneratedValue);
}

function isExpandableColumn(columnValues: ColumnValue[]) {
	return (
		columnValues.some((value) => isPlainObject(value)) ||
		columnValues.some(
			(value) => Array.isArray(value) && value.some(isPlainObject)
		)
	);
}

function isDateColumn(columnValues: ColumnValue[]) {
	return columnValues.every(isConvertibleToDate);
}

function isStringColumn(columnValues: ColumnValue[]) {
	return (
		columnValues.some(isString) ||
		columnValues.some(
			(value) => Array.isArray(value) && value.some(isString)
		)
	);
}
