import { isFallbackPrimaryColumn } from "#primary-column.ts";
import type {
  GridRows,
  GridSchema,
  InferColumnType,
  PluginConfig,
} from "#schema.ts";

import {
  isArrayOfObjects,
  isBoolean,
  isFunction,
  isISODateString,
  isNumber,
  isPlainObject,
  isString,
  type JSONValueOrUndefined,
} from "@jsoc/utils";

/**
 * Property in a `GridRow`
 */
export type ColumnKey = string;
/**
 * Value of a property in a `GridRow`.
 * - Note: As `GridRows` are generated from the `GridDataReadOnly`, the column value
 * 	can be one of the JSON value types (array, boolean, null, number, object, string)
 *	or undefined.
 */
export type ColumnValue = JSONValueOrUndefined;
/**
 * Mapping of `ColumnKey` with an array of the all corresponding `ColumnValues`
 * generated by `createColumnKeyValueMap` method
 */
export type ColumnKeyValueMap = Record<ColumnKey, ColumnValue[]>;
/**
 * Data type resolved for a particular `ColumnKey` based on the `GridRows`.
 */
export type ColumnDataType =
  | "arrayOfObjects"
  | "boolean"
  | "number"
  | "object"
  | "stringDate"
  | "string"
  | "unresolved";
/**
 * Method that will be used to resolve the `ColumnDataType` for a particular `ColumnKey`.
 * - It should return `false` if the `ColumnDataType` cannot be resolved.
 */
export type ColumnDataTypeResolverMethod = (
  columnValues: ColumnValue[],
) => ColumnDataType | false;
/**
 * `ColumnGenerator` method params object.
 */
export type ColumnGeneratorParams = {
  /**
   * `ColumnKey` of the column for which the column definition needs to be generated
   */
  columnKey: ColumnKey;
  /**
   * `ColumnDataType` of the column
   */
  columnDataType: ColumnDataType;
  /**
   * Schema of the grid that will contain the column
   */
  gridSchema: GridSchema;
};
/**
 * Default method that will be used to generate one column definition for a column `ColumnKey`.
 */
export type ColumnGenerator<C extends PluginConfig> = (
  params: ColumnGeneratorParams,
  /**
   * Definition overrides received from the corresponding `CustomColumnGenerator` of the `CustomColumnGeneratorByType`
   */
  overrides?: Partial<InferColumnType<C>>,
) => InferColumnType<C>;
/**
 * Custom method received from consumer that will be used to generate one column definition for a column `ColumnKey`.
 */
export type CustomColumnGenerator<C extends PluginConfig> = (
  params: ColumnGeneratorParams,
) => InferColumnType<C>;
/**
 * Mapping of `ColumnKey` and the resolved `ColumnDataType` for the `ColumnKey`
 *  - Generated by `createColumnDataTypeMap` method
 */
export type ColumnDataTypeMap = Record<ColumnKey, ColumnDataType>;
/**
 * Mapper that contains `ColumnGenerator`s for all the `ColumnDataType`s for the particular
 * Grid UI Component.
 * - Used by the `generateColumns` method to convert the `ColumnDataTypeMap` into an array of column
 * definitions.
 *
 * NOTE: Main motive of using mapper is to allow the consumer to reuse the default column definition
 * providers and in case, doesn't want to use any provider, then create its own implementation and
 * provide it through custom column definition providers.
 */
export type ColumnGeneratorByType<C extends PluginConfig> = Record<
  ColumnDataType,
  ColumnGenerator<C>
>;
/**
 * If provided, `generateColumns` method will use these methods to provide the column definitions for the Grid UI Component.
 * - It is an object containing 0 or more `CustomColumnGenerator`s to override the
 * 	corresponding default `ColumnGenerator`s for the `ColumnDataType`
 */
export type CustomColumnGeneratorByType<C extends PluginConfig> = Partial<
  Record<ColumnDataType, CustomColumnGenerator<C>>
>;

/**
 * Generates column definitions/configurations for the particular Grid UI Component.
 */
export function generateColumns<C extends PluginConfig>(
  gridSchema: GridSchema,
  defaultColumnGeneratorByType: ColumnGeneratorByType<C>,
  customColumnGeneratorByType?: CustomColumnGeneratorByType<C>,
): InferColumnType<C>[] {
  const columnKeyValueMap = createColumnKeyValueMap(gridSchema.meta.rows);
  const columnDataTypeMap = createColumnDataTypeMap(columnKeyValueMap);
  const columnDataTypeEntries = Object.entries(columnDataTypeMap);

  const columns = [];

  for (const [columnKey, columnDataType] of columnDataTypeEntries) {
    // TODO: merge customColumnGeneratorByType with defaultColumnGeneratorByType
    const columnGenerator =
      isPlainObject(customColumnGeneratorByType) &&
      isFunction(customColumnGeneratorByType[columnDataType])
        ? customColumnGeneratorByType[columnDataType]
        : defaultColumnGeneratorByType[columnDataType];

    const generatedColumn = columnGenerator({
      columnKey,
      columnDataType,
      gridSchema,
    });

    columns.push(generatedColumn);
  }

  return columns;
}

function createColumnKeyValueMap(plainRows: GridRows): ColumnKeyValueMap {
  const columnKeyValueMapper: ColumnKeyValueMap = {};

  /**
   * This approach ensures all ColumnValue[] arrays are have equal length === number of rows
   * CAVAETS:
   * 1. If there is even one missing value of a ColumnKey in rows, then the column data type
   * 	will become unresolved, this is due to implementation of `ColumnDataTypeResolverMethod`
   * 	as to resolve only if all values are of same type.
   * 2. First Row decides the order of column keys. Remaining rows only adds the column keys
   * 	that were not present in the previous rows.
   */
  const allColumnKeys = new Set<string>();
  for (const row of plainRows) {
    for (const key in row) {
      allColumnKeys.add(key);
    }
  }

  for (const row of plainRows) {
    for (const key of allColumnKeys) {
      columnKeyValueMapper[key] = columnKeyValueMapper[key] ?? [];
      columnKeyValueMapper[key].push(row[key]);
    }
  }

  // old method, doesn't include a undefined value if the key doesn't have value in a row but other row has
  // for (const row of plainRows) {
  // 	for (const [columnKey, columnValue] of Object.entries(row)) {
  // 		columnKeyValueMapper[columnKey] =
  // 			columnKeyValueMapper[columnKey] ?? [];
  // 		columnKeyValueMapper[columnKey].push(columnValue);
  // 	}
  // }

  return columnKeyValueMapper;
}

/**
 * Ordered list of column data-type resolvers.
 */
const COLUMN_DATA_TYPE_RESOLVER_LIST: ColumnDataTypeResolverMethod[] = [
  (colValues) => colValues.every(isArrayOfObjects) && "arrayOfObjects",
  (colValues) => colValues.every(isBoolean) && "boolean",
  (colValues) => colValues.every(isNumber) && "number",
  (colValues) => colValues.every(isPlainObject) && "object",
  (colValues) => colValues.every(isISODateString) && "stringDate", // DO NOT PLACE THIS BELOW string resolver
  (colValues) => colValues.every(isString) && "string",
];

function createColumnDataTypeMap(
  columnKeyValueMap: ColumnKeyValueMap,
): ColumnDataTypeMap {
  const columnSchemaMap: ColumnDataTypeMap = {};

  for (const [columnKey, columnValues] of Object.entries(columnKeyValueMap)) {
    if (isFallbackPrimaryColumn(columnKey)) {
      continue; // skip this column as data of this column is not part of actual GridDataReadonly
    }

    let resolvedDataType: ColumnDataType = "unresolved";
    for (const method of COLUMN_DATA_TYPE_RESOLVER_LIST) {
      const returnVal = method(columnValues);
      if (returnVal) {
        resolvedDataType = returnVal;
        break;
      }
    }

    columnSchemaMap[columnKey] = resolvedDataType;
  }

  return columnSchemaMap;
}
