import {
	areAllUnique,
	ensureArray,
	isConcreteObject,
	isNumber,
	isPlainObject,
	isString,
	type PlainObject,
} from '../utils';
import { type GridData, type IdColumnKey, FALLBACK_ID_COLUMN_KEY } from './';

/**
 * A row is a plain object generated by the `generateRows` from the `GridData`
 */
export type GridRow = PlainObject;
export type GridRows = Array<GridRow>;
/**
 * Value of `IdColumnKey` in a `GridRow`
 */
export type GridRowId = string | number;

/**
 * Returns an object containing `gridRows` and `gridIdColumnKey`
 * @param gridData JSON data received from the consumer
 */
export function generateRows(gridData: GridData): {
	gridRows: GridRows;
	gridIdColumnKey: IdColumnKey;
} {
	const gridDataCopy = structuredClone(gridData);
	let gridRows = ensureArray(gridDataCopy).filter(
		(row) => isPlainObject(row) && isConcreteObject(row)
	);
	let gridIdColumnKey: IdColumnKey;

	if (isExistingIdColumnValid(gridRows)) {
		gridIdColumnKey = 'id';
	} else {
		gridIdColumnKey = FALLBACK_ID_COLUMN_KEY;
		gridRows = assignFallbackIdColumnValues(gridRows);
	}

	return {
		gridRows,
		gridIdColumnKey,
	};
}

function isValidRowId(arg: unknown): arg is GridRowId {
	return isString(arg) || isNumber(arg);
}

function isExistingIdColumnValid(plainRows: GridRows): boolean {
	const isIdValidInEachRow = plainRows.every((row) => isValidRowId(row.id));
	const isIdUniqueInEachRow = areAllUnique(plainRows.map((row) => row.id));

	return isIdValidInEachRow && isIdUniqueInEachRow;
}

function assignFallbackIdColumnValues(plainRows: GridRows): GridRows {
	const updatedRows = plainRows.map((row, index) => ({
		...row,
		[FALLBACK_ID_COLUMN_KEY]: String(index),
	}));

	return updatedRows;
}
