import {
	areAllUnique,
	ensureArray,
	ensureString,
	isConcreteObject,
	isNumber,
	isPlainObject,
	isString,
} from '../utils';
import { type IdColumnKey, FALLBACK_ID_COLUMN_KEY } from './';

/**
 * https://github.com/microsoft/TypeScript/pull/33050
 */
export type JSONValue =
	| string
	| number
	| boolean
	| null
	| JSONValue[]
	| { [key: string]: JSONValue };
export type JSONValueOrUndefined = JSONValue | undefined;
export type JSONObject = Record<string, JSONValue>;
export type JSONObjectWithUndefined = Record<string, JSONValueOrUndefined>;
/**
 * Data provided by the consumer to the JsocGrid component
 */
export type GridData = JSONObjectWithUndefined | Array<JSONObjectWithUndefined>;
/**
 * Use GridDataReadonly to avoid mutating the JSON data provided by the consumer
 */
export type GridDataReadonly = Readonly<GridData>;
/**
 * A row is a plain object generated by the `generateRows` from the `GridDataReadonly`
 */
export type GridRow = JSONObjectWithUndefined;
export type GridRows = Array<GridRow>;
/**
 * Value of `IdColumnKey` in a `GridRow`
 */
export type GridRowId = string | number;

/**
 * Returns an object containing `gridRows` and `gridIdColumnKey`
 * @param gridData JSON data received from the consumer
 */
export function generateRows(gridData: GridDataReadonly): {
	gridRows: GridRows;
	gridIdColumnKey: IdColumnKey;
} {
	const gridDataCopy = structuredClone(gridData) as GridData;
	let gridRows = ensureArray(gridDataCopy).filter(
		(row) => isPlainObject(row) && isConcreteObject(row)
	);
	let gridIdColumnKey: IdColumnKey;

	if (isExistingIdColumnValid(gridRows)) {
		gridIdColumnKey = 'id';
	} else {
		gridIdColumnKey = FALLBACK_ID_COLUMN_KEY;
		gridRows = assignFallbackIdColumnValues(gridRows);
	}

	return {
		gridRows,
		gridIdColumnKey,
	};
}

function isValidRowId(arg: unknown): arg is GridRowId {
	return isString(arg) || isNumber(arg);
}

function isExistingIdColumnValid(plainRows: GridRows): boolean {
	const isIdValidInEachRow = plainRows.every((row) => isValidRowId(row.id));
	const isIdUniqueInEachRow = areAllUnique(plainRows.map((row) => row.id));

	return isIdValidInEachRow && isIdUniqueInEachRow;
}

function assignFallbackIdColumnValues(plainRows: GridRows): GridRows {
	const updatedRows = plainRows.map((row, index) => ({
		...row,
		[FALLBACK_ID_COLUMN_KEY]: ensureString(index),
	}));

	return updatedRows;
}
