import {
  type ColumnKey,
  type PrimaryColumnKey,
  GridError,
  getPrimaryColumnKey,
  type CustomColumnGeneratorByType,
} from "#grid/index.ts";
import { ensureArray, isArrayOfObjects } from "#utils/array.ts";
import { isConcreteObject, isPlainObject } from "#utils/object.ts";
import { isString, type JSONObjectWithUndefined } from "#utils/index.ts";

/**
 * Unique id of a `GridSchema` inside the `GridStore`
 */
export type GridId = string;
/**
 * Name of a `GridSchema`. Multiple `GridSchema` can have same name.
 */
export type GridName = string;
/**
 * Index of a `GridSchema` inside the `GridStore`
 */
export type GridIndex = number;
/**
 * Type of the data that can be used to generate a grid
 */
export type GridData =
  | string
  | JSONObjectWithUndefined
  | Array<JSONObjectWithUndefined>;
/**
 * This type is used to prevent modification of the grid data.
 */
export type GridDataReadonly = Readonly<GridData>;
/**
 * Single row. Refer `generateSchema` method for the implementation.
 */
export type GridRow = JSONObjectWithUndefined;
/**
 * Collection of `GridRow`s generated by the `generateSchema` method.
 */
export type GridRows = Array<GridRow>;
/**
 * Value of `PrimaryColumnKey` in a `GridRow`
 */
export type GridRowId = string | number;
/**
 * Object representing abstract location of a grid cell.
 */
export type GridCellLocation = {
  /**
   * `ColumnKey` which this cell corresponds to.
   */
  columnKey: ColumnKey;
  /**
   * Value of `PrimaryColumnKey` column in the row that contains this cell.
   * Instead of row index, row id is used here as it correctly identifies the row even if the rows are reordered.
   */
  rowId: GridRowId;
};
export interface GridOptions {
  data: GridDataReadonly;
  name?: GridName;
}
export interface GridOptionsWithId extends GridOptions {
  id: GridId;
}
export interface GridMeta {
  rows: GridRows;
  primaryColumnKey: PrimaryColumnKey;
}
export interface GridSchema {
  meta: GridMeta;
  options: GridOptionsWithId;
}
/**
 * Base type for any grid plugin config.
 */
export interface PluginConfig<TColumn = unknown> {
  /**
   * Internal property used to store the column type for type inference. Actual property name varies based on the plugin.
   */
  __columnType?: TColumn;
}
/**
 * Column type inferred from the `PluginConfig`
 */
export type InferColumnType<C extends PluginConfig> =
  C["__columnType"] extends infer T ? NonNullable<T> : never;
/**
 * Options for the `PluginConfigGenerator`
 */
export type PluginConfigGeneratorOptions<
  C extends PluginConfig = PluginConfig,
> = {
  customColumnGeneratorByType?: CustomColumnGeneratorByType<C>;
};
/**
 * Method that will be used to generate the `PluginConfig` for the grid plugin
 */
export type PluginConfigGenerator<C extends PluginConfig = PluginConfig> = (
  gridSchema: GridSchema,
  options?: PluginConfigGeneratorOptions<C>,
) => C;
/**
 * `GridSchema` with the `PluginConfig`
 */
export interface GridSchemaWithConfig<
  C extends PluginConfig,
> extends GridSchema {
  config: C;
}

// ------------------------------------------------------------------
// -------------------------- TYPES ENDED ---------------------------
// ------------------------------------------------------------------

/**
 * Default name that is used if the consumer didn't provide any name for the the root grid.
 */
export const DEFAULT_ROOT_GRID_NAME = "Grid";

/**
 * TODO: Add docs
 */
export function newGridSchema<C extends PluginConfig>(
  options: GridOptionsWithId,
  configGenerator: PluginConfigGenerator<C>,
  configGeneratorOptions?: PluginConfigGeneratorOptions<C>,
): GridSchemaWithConfig<C> {
  const schema = generateSchema(options);
  const config = configGenerator(schema, configGeneratorOptions);

  return { ...schema, config };
}

export function generateSchema(options: GridOptionsWithId): GridSchema {
  let dataClone;
  if (isString(options.data)) {
    try {
      dataClone = JSON.parse(options.data);
    } catch (e) {
      throw new GridError("Provided JSON is not valid.", e);
    }
  } else {
    dataClone = structuredClone(options.data);
  }

  assertIsValidGridData(dataClone);

  const rows = ensureArray(dataClone).filter(
    (row) => isPlainObject(row) && isConcreteObject(row),
  );
  const primaryColumnKey = getPrimaryColumnKey(rows);

  const meta = { rows, primaryColumnKey };
  return { meta, options };
}

export function assertIsValidGridData(arg: unknown): asserts arg is GridData {
  if (!isPlainObject(arg) && !isArrayOfObjects(arg)) {
    throw new GridError(
      "Provided grid data is not valid.",
      "Provided grid data is neither a JSON object nor an array of JSON objects.",
    );
  }
}
