import {
	isImageLink,
	getImageHtmlString,
	joinImageOrStringValues,
} from '@jsoc/core';
import { GridColDef, GridRenderCellParams } from '@mui/x-data-grid';
import { ColumnFactory, ColumnKey, isAutoGeneratedValue } from '@jsoc/core/grid';
import { JsocGridExpander } from '../../../components/JsocGridExpander';

export const COLUMN_FACTORY: ColumnFactory<GridColDef> = {
	string: getNewTextColumn,
	date: getNewDateColumn,
	expander: getNewExpanderColumn,
};

export function getNewTextColumn(id: ColumnKey): GridColDef {
	return {
		field: id,
		headerName: id,
		renderCell: (params: GridRenderCellParams) => {
			const { row, value } = params;
			if (isAutoGeneratedValue(value)) {
				return ''
			}
			if (Array.isArray(value)) {
				return joinImageOrStringValues(value);
			}
			if (isImageLink(value)) {
				return getImageHtmlString(value);
			}
			return value;
		},
	};
}

export function getNewDateColumn(id: ColumnKey): GridColDef {
	return {
		field: id,
		headerName: id,
		renderCell: (params: GridRenderCellParams) => {
			params.value;

			return 'Date Col';
		},
	};
}

// column-generator for expander-type column (whose data passes isExpandableColumn check)
export function getNewExpanderColumn(id: ColumnKey): GridColDef {
	return {
		field: id,
		headerName: id,
		renderCell: (params: GridRenderCellParams) => {
			const { row, value } = params;
			return <JsocGridExpander gridKey={id} gridData={value} />;
		},
	};
}
